Fixes typos in shape.py
mdtraj/mdtraj pull request #1634
Opened 2021-04-02 16:55 UTC by KirillShmilovich

fixes #1632

2021-04-02 18:28 UTC, nec4 approved these changes

2021-04-02 18:29 UTC, nec4 approved these changes

2021-04-02 18:30 UTC, nec4 commented on mdtraj/geometry/shape.py
>      """Compute the acylindricity of a trajectory.
All the changes look good, but the docs here still imply that the function computes the acylindricity instead of the relative shape anisotropy.

2021-04-02 18:32 UTC, nec4 requested changes
All the changes look great but I think that the docstring still implies that the acylindricity is being computed instead of the relative shape anisotropy.

2021-04-02 18:33 UTC, nec4 approved these changes

2021-04-02 18:45 UTC, nec4 commented
Thanks for making the changes! Everything looks great - just waiting for the tests to finish.

2021-04-02 22:22 UTC, nec4 commented
Alright - everything looks good to me!

2021-04-03 02:31 UTC, merged

2024-05-15 16:16 UTC, SamCox822 commented
@nec4 @KirillShmilovich 
I think these issues still exist in the documentation [here](https://mdtraj.org/1.9.4/api/generated/mdtraj.relative_shape_antisotropy.html#mdtraj.relative_shape_antisotropy) FYI.

2024-05-16 06:19 UTC, mattwthompson commented
That's an old version (1.9.4) but the bigger problem is the possibility that we haven't actually re-built and published docs in years ... (#1810?)